### ServerGoverner Configuration File

### Table of Contents:
## Administration
#  Banning
#  Muting
#  Jailing
#  Godding



### Administration ### 
## Banning ##
defaultBanTime: "1d"
maxBanTime: "30d"
defaultBanReason: "&4You have broken the rules!"

## Muting ##
blockCommandsWhileMuted:
- say
- me
- local
- msg

## Jailing ##
jailPosition:
  x: 000
  y: 100
  z: 000
setJailedInAdventureMode: false
muteJailed: false

## Godding ##
# the below two = <players, all, none>
preventGoddedDamage: all
preventGoddedAttack: players