name: ServerGoverner
main: xyz.teamhydroxide.servergoverner.Main
version: 3
website: http://teamhydroxide.org
authors: [MadScientist, Xenon]

anchored_content: &errmsg "[SG] ERROR: invalid syntax, see /<command>!"

commands:

  sg:
    description: General Data about the plugin
    usage: *errmsg
    permission: sgov
  ban:
    description: Banning players
    usage: *errmsg
    permission: sgov.admin.ban
  unban:
    description: Un-Banning players
    usage: *errmsg
    permission: sgov.admin.ban
  kick:
    description: Removing players from the server
    usage: *errmsg
    permission: sgov.admin.kick
  mute:
    description: Muting Players
    usage: *errmsg
    permission: sgov.admin.mute
  jail:
    description: Jailing Players
    usage: *errmsg
    permission: sgov.admin.jail
  god:
    description: Godding Players
    usage: *errmsg
    permission: sgov.admin.god
  chatclear:
    description: Clears chat
    usage: *errmsg
    permission: sgov.admin.chatclear


  quit:
    description: Leave the game.
    usage: *errmsg
    aliases: [q, leave]
    permission: sgov.commandquit
  home:
    description: Teleport to your home bed.
    usage: *errmsg
    aliases: [h]
    permission: sgov.home
  data:
    description: Provides information about a given player.
    usage: *errmsg
    aliases: [playerinfo]
    permission: sgov.data
  local:
    description: local chat
    usage: *errmsg
    permission: sgov.localchat
  lag:
    description: Prints data about the server.
    usage: *errmsg
    permission: sgov.lag